Upgrade jsch from 0.1.52 to 0.1.55 to fix CVE-2016-5725
prestodb/tempto pull request #281
Opened 2024-12-05 08:43 UTC by Dilli-Babu-Godari

**Description**

Upgrade jsch from 0.1.52 to 0.1.55 to fix CVE-2016-5725

Upgrading the jsch library from version 0.1.52 to 0.1.55 addresses CVE-2016-5725, which is a directory traversal vulnerability in JCraft JSch before version 0.1.54. This vulnerability allowed remote SFTP servers to write to arbitrary files on Windows when using ChannelSftp.OVERWRITE mode, via a ..\ (dot dot backslash) in a recursive GET command.

Build Successful.
<img width="802" alt="Screenshot 2024-12-05 at 2 11 34 PM" src="https://github.com/user-attachments/assets/df086c5d-6437-48d8-8687-8a635700f477">

2024-12-10 04:55 UTC, aaneja approved these changes

2024-12-10 04:58 UTC, aaneja commented
I could pull this locally and build & run tests. We need to have a release pipeline to publish updated artifacts.  
I'm not sure how we've done this in the past, but I see there were signing + upload steps added in https://github.com/prestodb/tempto/pull/3/

If we cannot dig through history to figure out how we did releases, I do have a branch which uses a more up-to-date gradle that I think we should switch to for releases

2024-12-10 07:26 UTC, Dilli-Babu-Godari commented
> I could pull this locally and build & run tests. We need to have a release pipeline to publish updated artifacts. I'm not sure how we've done this in the past, but I see there were signing + upload steps added in #3
> 
> If we cannot dig through history to figure out how we did releases, I do have a branch which uses a more up-to-date gradle that I think we should switch to for releases

<img width="854" alt="Screenshot 2024-12-10 at 12 48 37 PM" src="https://github.com/user-attachments/assets/01a308cf-f3fb-4ac2-8a5c-c7e47a0628a8">

I tried adding build scripts on GitHub following this PR: https://github.com/prestodb/airlift/pull/77/files in my forked repository, as suggested by Tim Meehan. However, I'm encountering a build failure. The build is failing at the signingArchives task for the Java 8 build, and I'm currently investigating the issue.

<img width="1276" alt="Screenshot 2024-12-10 at 12 38 52 PM" src="https://github.com/user-attachments/assets/354c0b32-60d6-4401-a80a-55f311c6b488">

I also noticed a lot of warnings while using Java 8, and during the Java 11 compilation, it failed at the 'CompileJava' task with a couple of errors.

<img width="1287" alt="Screenshot 2024-12-10 at 12 45 57 PM" src="https://github.com/user-attachments/assets/b8d9ad63-6a31-45e9-abcb-07ef590a3c63">
If you have any insights on this, please let me know.

2024-12-10 18:44 UTC, ZacBlanco commented
@Dilli-Babu-Godari for both CI in the matrix you should set `skipSigning` to false in the gradle properties. The example property is defined in the sample `gradle.properties` in the root of the repository. You might need an extra step in the CI script to generate the file, or you might be able to pass it on the command line with something like `-PskipSigning=true` or `-DskipSigning=true`

2024-12-10 20:49 UTC, ZacBlanco commented
Also regarding the Java 11 compatibility. I don't think we need to compile to Java 11. We probably just need it to compile to java 8 and for the tests to pass if executed with Java 11. The gradle build may need to be updated for that, but I'm not sure.

2024-12-12 07:59 UTC, Dilli-Babu-Godari commented
> Also regarding the Java 11 compatibility. I don't think we need to compile to Java 11 bytecode. We probably just need it to compile to java 8 and for the tests to pass if executed with Java 11. The gradle build may need to be updated for that, but I'm not sure.
I will try and check with Java 8 for now.

2024-12-12 08:00 UTC, Dilli-Babu-Godari commented
> Also regarding the Java 11 compatibility. I don't think we need to compile to Java 11 bytecode. We probably just need it to compile to java 8 and for the tests to pass if executed with Java 11. The gradle build may need to be updated for that, but I'm not sure.

I will try and check with Java 8 for now.

2024-12-12 09:38 UTC, Dilli-Babu-Godari commented
> @Dilli-Babu-Godari for both CI in the matrix you should set `skipSigning` to false in the gradle properties. The example property is defined in the sample `gradle.properties` in the root of the repository. You might need an extra step in the CI script to generate the file, or you might be able to pass it on the command line with something like `-PskipSigning=true` or `-DskipSigning=true`

@ZacBlanco I've implemented the changes based on your feedback and have raised a separate PR for them. You can find the PR here: [#282](https://github.com/prestodb/tempto/pull/282). Could you please take a look when you have a moment?

2024-12-13 18:26 UTC, ZacBlanco commented
@Dilli-Babu-Godari can you force-push again to this branch to trigger the new GH action

2024-12-13 18:46 UTC, Dilli-Babu-Godari commented
> @Dilli-Babu-Godari can you force-push again to this branch to trigger the new GH action

I've rebased with master and force-pushed the changes to the branch. Everything is working as expected, and the check has successfully passed.

2024-12-13 18:46 UTC, ZacBlanco requested changes
last thing, otherwise lgtm

2024-12-13 18:49 UTC, ZacBlanco approved these changes

2024-12-13 18:51 UTC, Dilli-Babu-Godari commented on .gitignore
> +!gradle.properties
Removed this. Could you please merge the change if everything looks fine ?

2024-12-13 18:52 UTC, ZacBlanco commented
I don't have permissions. @tdcmeehan should be able to merge this

2024-12-13 18:54 UTC, merged