[DRAFT] Modernize tempto
prestodb/tempto pull request #283
Opened 2024-12-17 07:58 UTC by aaneja

- Upgrade Gradle to 8.11
- Update core dependencies to more recent versions
- Remove unused NameService/NameServiceDescriptor implementations

2025-01-07 20:43 UTC, wanglinsong commented
https://github.com/prestodb/tempto/issues/284

2025-01-17 13:22 UTC, aaneja commented on build.gradle
> +                groupId 'com.github.aaneja.tempto'
Still need to figure out how publishing would work

2025-01-17 13:22 UTC, aaneja commented on build.gradle
> +                version 'jdk8_snapshot'
Need to change the version

2025-01-21 17:34 UTC, ZacBlanco requested changes
Just some small things. Thanks for this effort!

2025-01-21 17:34 UTC, ZacBlanco commented on build.gradle
> +                            name = 'PrestoDb'
nit: Maybe `PrestoDB developers`?

2025-01-21 17:34 UTC, ZacBlanco commented on build.gradle
> +                            email = 'presto@prestodb.io'
does this email actually exist?

2025-01-21 17:34 UTC, ZacBlanco commented on jitpack.yml
> +  - ./gradlew PskipSigning=true -Ptempto_group=com.github.aaneja.tempto clean publishToMavenLocal
```suggestion
  - ./gradlew -PskipSigning=true -Ptempto_group=io.prestodb.tempto clean publishToMavenLocal
```

2025-01-21 17:36 UTC, ZacBlanco commented
Also, consider adding gradle dependency caching in the CI? See here for example: https://github.com/actions/setup-java?tab=readme-ov-file#caching-gradle-dependencies

2025-01-21 19:49 UTC, ZacBlanco commented on jitpack.yml
> +  - ./gradlew PskipSigning=true -Ptempto_group=com.github.aaneja.tempto clean publishToMavenLocal
Actually, tempto_group should probably be `com.github.prestodb.tempto`?

2025-01-21 20:10 UTC, wanglinsong commented on build.gradle
> +                            email = 'presto@prestodb.io'
I think so. Otherwise, we can create it.

2025-01-22 10:15 UTC, aaneja commented on build.gradle
> +                            email = 'presto@prestodb.io'
I think we can drop this block - I don't see it on our Presto pom's, e.g https://repo1.maven.org/maven2/com/facebook/presto/presto-cli/0.290/presto-cli-0.290.pom

2025-01-22 10:16 UTC, aaneja commented on jitpack.yml
> +  - ./gradlew PskipSigning=true -Ptempto_group=com.github.aaneja.tempto clean publishToMavenLocal
I wanted to use my own groupid for testing. Since this is jitpack related, it will have no bearing on the actual release artifacts

2025-01-22 10:29 UTC, aaneja commented on jitpack.yml
> +  - ./gradlew PskipSigning=true -Ptempto_group=com.github.aaneja.tempto clean publishToMavenLocal
I will delete this file

2025-01-22 16:03 UTC, ZacBlanco approved these changes

2025-01-23 11:59 UTC, imjalpreet reviewed
@aaneja thank you! Just some minor clarifications, otherwise LGTM!

Also, I just noticed tempto is still using `io.prestodb.*` package names. Maybe in a separate effort we can refactor it to align with other presto packages to use `com.facebook.presto.*`

2025-01-23 11:59 UTC, imjalpreet commented on gradlew
> +# Copyright © 2015-2021 the original authors.
Just for my understanding, should this be 2025 or is this script auto-generated? (https://www.apache.org/licenses/LICENSE-2.0#apply)

2025-01-23 11:59 UTC, imjalpreet commented on gradlew.bat
> +
nit: 2 successive empty/new lines?

2025-01-23 11:59 UTC, imjalpreet commented on tempto-core/build.gradle
> +
Do we want to keep this commented or remove it?

2025-01-23 11:59 UTC, imjalpreet commented on tempto-runner/src/main/java/io/prestodb/tempto/runner/TemptoRunner.java
> -        TemptoNameServiceDescriptor.enableHostMapping();
Again, just for my understanding, do we not require this anymore? Does it happen automatically now?

2025-01-23 14:42 UTC, aaneja commented on gradlew
> +# Copyright © 2015-2021 the original authors.
This is auto generated. I can fix this manually

2025-01-23 14:42 UTC, aaneja commented on tempto-core/build.gradle
> +
Good catch, will remove

2025-01-23 14:45 UTC, aaneja commented on gradlew.bat
> +
Auto generated, so leaving as-is

2025-01-23 16:03 UTC, imjalpreet approved these changes

2025-01-23 16:04 UTC, tdcmeehan approved these changes

2025-01-23 16:04 UTC, merged